//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion1.License.Validation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fusion1.License.Validation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIDDTCCAfWgAwIBAgIUS/IyBw4achgYN5TMO6kZ3SiSSQ4wDQYJKoZIhvcNAQEL
        ///BQAwFjEUMBIGA1UEAwwLTGljZW5zZVNpZ24wHhcNMjIwMTE2MDExMjM4WhcNMzIw
        ///MTE0MDExMjM4WjAWMRQwEgYDVQQDDAtMaWNlbnNlU2lnbjCCASIwDQYJKoZIhvcN
        ///AQEBBQADggEPADCCAQoCggEBAKz8Sns0P0484QZ8X97ST05i00hhOj3Ss/k+ICnm
        ///FduxQ2y6VdxSRoLANte7ElsBVLIufURKYnGGj7yjSkOaJKXOXznilhSMSVvky5Iw
        ///hKgvDFZFBiE5syPyXB5/rx91J2fqnIEDyypHjFs5A8Sfr9fXXdk5lr8kzc64aB79
        ///ES2YTqYsQwmFTK9ACWb90Cdg+JzN9hCebyQHEo6lqbi16ymzvN3s/PXOWcWePNNH
        ///TwPdoLsMWtYJrXsfmz/AivQWZQoflJ9w1Hfb5uHibxjozo6oqG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
    }
}
